#!/bin/bash

release_file=/etc/os-release
logfile=/var/log/updater.log
errorlog=/var/log/updater_errors.log

if grep -q "Arch" $release_file
then
	# the host is Arch-based, run the pacman update command
	sudo pacman -Syu 1>>$logfile 2>>$errorlog
	if [ $? -ne 0 ]
	then
		echo "An error occurred, please check the $errorlog file"
	fi
fi
	# Alternatively, the host is Pop_OS, Debian or Ubuntu based
if grep -q "Pop" $release_file ||
   grep -q "Debian" $release_file || 
   grep -q "Ubuntu" $release_file
then
	sudo apt update -y 1>> $logfile 2>> $errorlog
	if [ $? -ne 0  ]
	then	
		echo "An error occurred, please check the $errorlog file"
	fi
	sudo apt dist-upgrade -y 1>> $logfile 2>> $errorlog
	if [ $? -ne 0  ]
	then
		echo "An error occurred, please check the $errorlog file"
	fi
fi
