#!/bin/bash

# A script to check some system info


DELAY=3 # time before returning results

while [[ "$REPLY" != 0 ]]; do
	clear
	cat <<- _EOF_
		Please Select:

		1. Display System Information
		2. Display Disk Space
		3. Display Home Space Utilization
		4. Display Current Power
		0. Quit

	_EOF_
	read -p "Enter selection [0-4] > "

	if [[ "$REPLY" =~ ^[0-4]$ ]]; then
		if [[ $REPLY == 0 ]]; then
			echo ""
			sleep 1
			break
		fi
		if [[ $REPLY == 1 ]]; then
			echo "Hostname: $HOSTNAME"
			uptime
			sleep "$DELAY"
		fi
		if [[ $REPLY == 2 ]]; then
			df -h
			sleep "$DELAY"
		fi
		if [[ $REPLY == 3 ]]; then
			if [[ "$(id -u)" -eq 0 ]]; then
				echo "Home Space Utilization (all users)"
				du -sh /home/*
			else
				echo "Home Space Utilization ($USER)"
				du -sh "$HOME"
			fi
			sleep "$DELAY"
		fi
		if [[ $REPLY == 4 ]]; then
			acpi -V                     # I need to send this to the terminal
			sleep "$DELAY"
		fi
	else
		echo "Invalid entry."                # This is always running no matter what(problem)
		sleep "$DELAY"
		
	fi
done
echo "Program terminated."
echo ""
			
