#!/bin/bash

lines=$(ls -lh $1 | wc -l)                                  # wc - word count

# Controlling for anything other than 1 argument
if [ $# -ne 1 ]
then
	echo "This script requires exactly one directory path passed to it."
	echo "You gave it $#. Please try again."
	exit 1
fi


# Empty word counts (=) folders that do not exist
if [ $lines -ne 0 ]
then
	echo "You have $(($lines-1)) objects in the '$1' directory"
fi
