#!/bin/bash

a=0
b=0
c=0
d=0

while true 
do
	echo "--$a$b$c$d--"

	echo "Please enter four values of 0 or 1:"
	read a
	read b
	read c
	read d

	if [ "$a" -ne 1 ] && [ "$a" -ne 0 ] || \
	   [ "$b" -ne 1 ] && [ "$b" -ne 0 ] || \
	   [ "$c" -ne 1 ] && [ "$c" -ne 0 ] || \
	   [ "$d" -ne 1 ] && [ "$d" -ne 0 ]; then
	
		echo "Enter only valid numbers."
	
        elif [ "$a" -eq 0 ] && \
             [ "$b" -eq 0 ] && \
             [ "$c" -eq 0 ] && \
	     [ "$d" -eq 0 ]; then

		echo "--$a$b$c$d--"
		echo "We're done here."
		
		break
	fi
done

# NOTE: again, pay attention to the '\' which allows for continuation
# We can implement code, with regEx, in order to check if the input is not an integer - this way we can gracefully inform the user to input the correct values, instead of getting an automatic system error:

# Check to see if the input is an integer
#if ! [[ $a =~ ^[0-9]+$ ]] || \
#       ! [[ $b =~ ^[0-9]+$ ]] || \
#       ! [[ $c =~ ^[0-9]+$ ]] || \
#       ! [[ $d =~ ^[0-9]+$ ]]; then
#        echo "Enter only valid integer numbers."
#        continue
#    fi
#
# Convert inputs to integers
#    a=$((10#$a))
#    b=$((10#$b))
#    c=$((10#$c))
#    d=$((10#$d))	
