#!/bin/bash


# Just to showcase some table options for simple scripts and nice tables
# Instead of always using '*', '|', '/', etc, we can use these symbols:

# {╣, ═, ╝, ╚, ╔, ╗, ║, ╠, ╦, ╩, ╬}


# Case in point:


echo "╔═════════════╦═════════╗"
echo "║ This is how ║ A pretty║"
echo "║they tell me ║ readable║"
echo "║  the world  ║book, if ║"
echo "║ is going to ║I'm being║"
echo "║    end.     ║honest.  ║"
echo "╠═════════════╬═════════╣"
echo "║Mr. Whiskers ║         ║"
echo "║             ║    A    ║"
echo "║    \_/      ║  Mighty ║"
echo "║   (o.o)     ║         ║"
echo "║     U       ║  Mouse  ║"
echo "╚═════════════╩═════════╝"
