#!/bin/bash

echo "Enter the folder you want: "
read dir_name

if [[ -d "$dir_name" ]]; then
	if cd $dir_name; then
		echo rm * # TESTING                        # (1)
	else
		echo "Cannot cd to '$dir_name'" >&2
		exit 1
	fi
else
	echo "No such directory: '$dir_name'" >&2
	exit 1
fi
exit # TESTING                                       # (2)

# NOTES:
#
# (1) We are placing here an echo, to have the command printed into the terminal
# and not actually deleted. Note that this will print the files to be deleted
#
# (2) The exit command is making sure that the program stops here and doesn't
# keep on going, carrying out extra commands
