#!/bin/bash

# Syntax Errors

number=1

if [ $number = 1 ]; then
	echo "Number is equal to 1.                    # (1)
else
	echo "Number is not equal to 1."
fi

# NOTES:
#
# (1) There are no finishing commas
#
# error:
#
# line 10: unexpected EOF while looking for matching (commas)
#
# The program is breaking when it closes the commas and then doesn't
# find a proper ending to the program. Notice that the commas are only
# ending at line 10, after 'echo'
