#!/bin/bash

number=1

if [ $number=1 ]; then
	echo "Number is equal to 1.
else
	echo "Number is not equal to 1."
fi

# error:
# ./commonErrors: line 8: unexpected EOF while looking for matching `"'
#
# The program is breaking when it closes the commas and then doesn't 
# have a proper termination, at line 8.
# 'syntax on' can be used with vim to highlight where the quoted text is
