#!/bin/bash

finished=0 	                    	                                  # (1)

while [ $finished -ne 1  ] 		                                      # (2)
do
	echo "╔═══════════════════════════════════╗"
	echo "║What is your favorite Linux distro?║"
	echo "╠═══════════════════════════════════╣"
	echo "║  1 - Arch                         ║"
	echo "║  2 - CentOS                       ║"
	echo "║  3 - Debian                       ║"
	echo "║  4 - Mint                         ║"
	echo "║  5 - Ubuntu                       ║"
	echo "║  6 - Something else...            ║" 
	echo "║  7 - Exit the script              ║"
	echo "╚═══════════════════════════════════╝"

	read distro;                                                      # (3)

	case $distro in                                                   # (4)
		1) echo "Arch is a rolling release.";;
		2) echo "CentOS is popular on servers.";;
		3) echo "Debian is a community distribution.";;
		4) echo "Mint is popular on desktops and laptops.";;
		5) echo "Ubuntu is popular on both servers and computers.";;
		6) echo "There are many distributions ou there.";;
		7) finished=1 ; echo "Thank you for your time!";;
		*) echo "You didn't enter an appropriate choice.";;           # (5)
	esac                                                              # (6)
done                            									  # (7)

# NOTES:
#
# (1) 'finished' is a variable that is equal to 0
#
# (2) As long as 'finished' isn't '1', this loop will run
#
# (3) This is to take the input from the user and adding that to 'distro'
#
# (4) Showcasing the 'cases'
#
# (5) Notice that '*' is covering any other alternative, like an else
#     if nothing else was picked
#
# (6) Closing the 'case'
#
# (7) As per usual, the while loop is opened with 'do' and closed with 'done'
