#!/bin/bash

myArray=()

# Creating the player list
while [ true ]
do
	echo "Enter the player's name, or press 0 to finish entering users:"
	read newUser

	if [ "$newUser" != 0 ]; then
		myArray+=("$newUser")
	else 
		break
	fi
done

# Number of players
array_length=${#myArray[@]}


# Printing the list of users - for testing purposes
for ((item = 0; item < array_length; item++))
do
	echo "${myArray[item]}"
done

# Function to randomly shuffle the list
shuffle_array() {
	local i j temp
	for ((i = $((array_length - 1)); i > 0; i--)); do
		j=$((RANDOM % (i + 1)))
		temp="${myArray[i]}"
		myArray[i]="${myArray[j]}"
		myArray[j]="${temp}"
	done
}

# Calling the function
shuffle_array


# Printing the user list, reshuffled and with their secret friend announced
for ((item = 0; item < array_length; item++))
do

	if [ "$item" -eq "$(($array_length - 1))" ]; then
		echo "${myArray[item]} has ${myArray[0]} as a s.s.friend"
	else
		echo "${myArray[item]} has ${myArray[item+1]} as a s.s.friend"
	fi
done
