#!/bin/bash

myArray=()

# Creating the player list
while [ true ]
do
	echo "Enter the player's name, or press 0 to finish entering users:"
	read newUser

	if [ "$newUser" != 0 ]; then
		myArray+=("$newUser")
	else 
		break
	fi
done

# Number of players
array_length=${#myArray[@]}


# Printing the list of users - just for control
echo "List of players:"
for ((item = 0; item < array_length; item++))
do
	echo "${myArray[item]}"
done

# Function to randomly shuffle the list
shuffle_array() {
	local i j temp
	for ((i = $((array_length - 1)); i > 0; i--)); do
		j=$((RANDOM % (i + 1)))
		temp="${myArray[i]}"
		myArray[i]="${myArray[j]}"
		myArray[j]="${temp}"
	done
}

# Calling the function
shuffle_array

# Creating folder to store the messages to the players
mkdir /home/SecretFriend/ 2> /dev/null
targetUser=""

# Sending each message to each user file
for ((item = 0; item < array_length; item++))
do
	if [ "$item" -eq "$(($array_length - 1))" ]; then
		targetUser="${myArray[item]}"
		targetFile="/home/SecretFriend/$targetUser"
		touch "$targetFile"
		echo -e "Olá, ${myArray[item]}! \n
			Aposto que gostarias de saber qual a identidade to teu amigo secreto. \n\
			Pois bem, o teu amigo secreto é: \n\n\
			${myArray[0]} \n\n\
			Shhhh! É segredo... \n\
			Feliz Natal!" > "$targetFile"
	else
		targetUser="${myArray[item]}"
		targetFile="/home/SecretFriend/$targetUser"
		touch "$targetFile"
		echo -e "Olá, ${myArray[item]}! \n
			Aposto que gostarias de saber qual a identidade to teu amigo secreto. \n\
			Pois bem, o teu amigo secreto é: \n\n\
			${myArray[item+1]} \n\n\
			Shhhh! É segredo... \n\
			Feliz Natal!" > "$targetFile"
	fi
done
