#!/bin/bash

# This is an adaptation of the more simplistic old-world code of SecretSanta-Mk1
# NOT a final version. In this version we just create the groups and add the users
# Mk3 will (hopefully) deal with the sorting of names appropriately
# It will also hold the base-rules that guide this 'game'.


# Defining the groups (families) as associative arrays. User decision
declare -A groups

echo "How many families will be playing?"
read num_groups

# Initialize groups array with empty arrays
for ((i = 1; i <= num_groups; i++)); do
    list_name="List$i"
    groups["$list_name"]=""
done

# Populate the groups with users
for ((i = 1; i <= num_groups; i++)); do
	list_name="List$i"
	echo "$list_name:"

	while true; do
		echo "Enter the player's name, or press 0 to finish entering users for this list:"
		read newUser

		if [ "$newUser" != 0 ]; then
			groups["$list_name"]+=" $newUser"
		else 
			break
		fi
	done
done

# Test. Let's read the users
for ((i = 1; i <= num_groups; i++)); do
	list_name="List$i"
	echo "Users in $list_name:"
	for user in ${groups["$list_name"]}; do
		echo "$user"
	done
done
