#!/bin/bash

echo "
\$0 = $0
\$1 = $1
\$2 = $2
\$3 = $3
\$4 = $4
\$5 = $5
\$6 = $6
\$7 = $7
\$8 = $8
\$9 = $9
\$10 = ${10}
"



# NOTES:
#
# (0) $0 will always contain the first item appearing on the
#        command line. If we add more arguments (parameters)
#        they will appear in the output
#    
#        Note that we have to do ${10} to actually read 2 
#        digits
#
